/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x20170913;

import javax.swing.JOptionPane;

/**
 *
 * @author Tanulo
 */
public class SzemelyiGUI extends javax.swing.JFrame {

    /**
     * Creates new form SzemelyiGUI
     */
    public SzemelyiGUI() {
        initComponents();
        futas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUjra = new javax.swing.JButton();
        lbHely = new javax.swing.JLabel();
        lbEvszam = new javax.swing.JLabel();
        lbNem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eredmény"));

        btnUjra.setText("Újra");
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        lbHely.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHely.setText(" ");

        lbEvszam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEvszam.setText(" ");

        lbNem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNem.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEvszam, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 136, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbHely, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUjra)
                .addGap(7, 7, 7)
                .addComponent(lbHely)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEvszam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNem)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
       futas();
    }//GEN-LAST:event_btnUjraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzemelyiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzemelyiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzemelyiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzemelyiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzemelyiGUI().setVisible(true);
            }
        });
        
    }
    
        private void futas () {
            String szemsz;
            try {
                 do {
                    szemsz = JOptionPane.showInputDialog(rootPane, 
                        "Adja meg a személyi számát! (11 szám)",
                        "Bekérés", HEIGHT);
                } while (szemsz.length() != 11);
                 
                String evszam1 = Character.toString(szemsz.charAt(1));
                String evszam2 = Character.toString(szemsz.charAt(2));
                String evszamossz = evszam1 + evszam2;
                int evszam = Integer.parseInt(evszamossz);
        
                if (evszam > 96 || evszam < 17) {
                    lbEvszam.setText("1996 utáni személyi.");
                    hatfelett(szemsz);
                } else if (evszam <= 96) {
                    lbEvszam.setText("1997 előtti személyi.");
                    hetalatt(szemsz);
                }
                nemek(szemsz);
            } catch (Exception e) {
                
            }
        }
    
    
    private void hatfelett(String szemsz) {
        int osszeg = 0;
        for (int i = 0; i < 10; i++) {
            osszeg += (10-i) * Integer.parseInt(Character.toString(szemsz.charAt(i)));
        }
        int modulo = osszeg%11;
        
        if (Integer.parseInt(Character.toString(szemsz.charAt(10))) != modulo) {
            lbHely.setText("Helytelen személyi.");
        }
        else lbHely.setText("Helyes személyi.");
    }

    private void hetalatt(String szemsz) {
        int osszeg = 0;
        for (int i = 0; i < 10; i++) {
            osszeg += (i+1) * Integer.parseInt(Character.toString(szemsz.charAt(i))); 
        }
        int modulo = osszeg%11;
        
        if (Integer.parseInt(Character.toString(szemsz.charAt(10))) != modulo) {
            lbHely.setText("Helytelen személyi.");
        }
        else lbHely.setText("Helyes személyi.");
    }
    
    private void nemek (String szemsz) {
        int elsoSzam = Integer.parseInt(Character.toString(szemsz.charAt(0))); 
        
        if (elsoSzam % 2 == 0) {
            lbNem.setText("A személyi szám nőé.");
        }
        else lbNem.setText("A személyi szám férfié.");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUjra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEvszam;
    private javax.swing.JLabel lbHely;
    private javax.swing.JLabel lbNem;
    // End of variables declaration//GEN-END:variables
}
